[tools]
usage = "latest"
node = "22"
sbt = "latest"
java = "corretto-17"
yarn = "latest"
"npm:brighterscript" = "latest"
rust = "latest"
"npm:prettier" = "latest"
"npm:aws-cdk" = "latest"
stylua = "latest"
"npm:opencode-ai" = "latest"
"cargo:parqeye" = "latest"
neovim = "latest"
"github:junegunn/fzf" = "latest"
tmux = "latest"
aws-cli = { version = "latest", symlink_bins = "true" }
gh = "latest"
lazygit = "latest"
coursier = "latest"
ripgrep = "latest"
"npm:claude" = "latest"
python = "latest"
"npm:@mariozechner/pi-coding-agent" = "latest"

[settings]
experimental = true
